name: Deploy

on:
  push:
    branches:
      - master
    
jobs:    
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    env:
      baseDir: '~/github/larapeak'
      releaseName: '${{ github.run_id }}'

    steps:    
      - name: 🌀 Clone repository
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          script: |
            cd ${{ env.baseDir }}/releases
            mkdir ${{ env.releaseName }}
            git clone --depth 1 https://github.com/larapeak/larapeak.com.git ${{ env.releaseName }}
            
      - name: 🎻 Run composer
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          script: |
            cd ${{ env.baseDir }}/releases/${{ env.releaseName }}
            composer install --optimize-autoloader --no-dev

      - name: 🌅 Generate assets
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          script: |
            cd ${{ env.baseDir }}/releases/${{ env.releaseName }}
            npm install
            npm run prod
            php artisan clear-compiled

      - name: 🔗 Update symlinks
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          script: |
            # Remove the storage directory and replace with persistent data
            rm -rf ${{ env.baseDir }}/releases/${{ env.releaseName }}/storage
            cd ${{ env.baseDir }}/releases/${{ env.releaseName }}
            ln -s ~/github/larapeak/persistent/storage storage

            # Import the environment config
            ln -s ~/github/larapeak/persistent/.env .env

      - name: 📀 Backup database
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          script: |
            cd ${{ env.baseDir }}/releases/${{ env.releaseName }}
            php artisan backup:run

      - name: 🙈 Migrate database
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          script: |
            cd ${{ env.baseDir }}/releases/${{ env.releaseName }}
            php artisan migrate --force
            
      - name: 🙏 Bless release
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          script: |
            cd ${{ env.baseDir }}
            ln -s ~/github/larapeak/releases/${{ env.releaseName }} current
            cd current
            php artisan config:clear
            php artisan config:cache
            php artisan route:clear
            php artisan route:cache
            php artisan view:cache

      - name: 🚾 Clean up old releases
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          script: |
            cd ${{ env.baseDir }}/releases
            ls -dt ${{ env.baseDir }}/releases/* | tail -n +4 | xargs -d "\n" sudo chown -R forge .;
            ls -dt ${{ env.baseDir }}/releases/* | tail -n +4 | xargs -d "\n" rm -rf;
