name: Deploy

on:
  push:
    branches:
      - master
    
jobs:    
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    env:
      baseDir: '~/github/larapeak'
      releaseName: '${{ github.run_id }}'

    steps:    
      - name: 🌀 Clone repository
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          script: |
            cd ${{ env.baseDir }}/releases
            mkdir ${{ env.releaseName }}
            git clone --depth 1 https://github.com/larapeak/larapeak.com.git ${{ env.releaseName }}
            
      - name: 🎻 Run composer
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          script: |
            cd ${{ env.baseDir }}/releases/${{ env.releaseName }}
            composer install --optimize-autoloader --no-dev
            
      - name: 🙈 Migrate database
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          script: |
            cd ${{ env.baseDir }}/releases/${{ env.releaseName }}
            php artisan migrate --force
            
      - name: 🙏 Bless release
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          script: |
            cd ${{ env.baseDir }}
            ln -s ~/github/larapeak/releases/${{ env.releaseName }} current
            php artisan config:cache
            php artisan route:cache
            php artisan view:cache
